sudo: false
language: java
jdk:
- oraclejdk8
script:
- test/run.sh
notifications:
  slack:
    secure: Nud42lkI3PdTkQReH/MpZK2ZOFPYQPV+VxQImUj1xTT2gQ1jJV+W0EFL1gjMvsEE20mxadUz0QHRbHa/EJmbmpU3DasBs27nAo8swGH/Y9bmZJe/E0hLmdq/sZSh18kxKXSgN6N51vqW2hz68az6pTTiGZCohRwFN5HwWnB0gB4Ezx6JWHlBuVozQazA3fNK6A7THgYS0weytfCFGUcMoRj+pU2FSP1/EoFlLiufl51OsY8LXPp/GFvZVyFPUdGQtnByCoQhq4OTzN3/tmWA83ncxAomHE6PyaI35eKEt9Rs1WQlROjOjDxcqMobZmV7jhVLSYkSYmqtZB8usZu9PULdfIE6WAtZr2m6rmRanFX5WMBFFHLrZHlQS0Bh7fGM6+Q2o1qqfUS8wDth3TfJrQpfFneo1vP3bZVactCoEpSQHOpsGZLES6UXOe6mYXLKAuFrtMCDKBFsB/EG0o0PH92N0KNlS1fy09t1k6V5HMDNwOSJYavT3CoKi2a7Z5bNMhorvSHjUcP7vZKd8/qHp1ZotWbW6UdNiVa3PBrI22tHKokYzFeV+7L3ZkOIzecinb0FDysAHxFFYWF8tE3qbvPq9BY59mnmnSdCMxDwIRG18EqC7IoxFqb1OJYk8cAFMLCYRC/M2KG05MPxBUxPx5RuX6EODRivnLKT+FP5vKU=
