sudo: false
language: java
jdk:
- oraclejdk8
script:
- test/run.sh
notifications:
  slack:
    secure: Pe3gkjhJsw/wTUwzznlSm/UQ4zkWLEq77YiDfkeaX1olfnJT+oX5xVQG1lkQ6zKS9j3p20GnJ6U6b0srZSrLV0MDA7NgO+9BndaONj29vdMf/C5gsIvOdoeg9o23/r4ge0DSlWBwBEdqfS2v6IDZ/T/OGX/sqgcOCcKnLyiF3Vep0Qx4aI7oC3cvWfv9lX8m14pHnE4xls1IJCkWl/cw/BZlnFLJhmVntpSZoaigM3WAeJzWVYOrIg4F+7TjExZzHXRdhIUI5nqcNoOHUuHYGllOPz1smAbv/GDyy9DUx0vgrUOeID2NV4FEIUMIAcVah1pYCk7B267LX8JoY0uurqXFKkwLvDgeaQ0KhFkbsJPdYSS8VpW05S0WNrwfkoMTV3tCVOOvz90qmuG5Nlt7K4z4lHbok77wsLLJ4vKyKrT6YAbim/lzacGbx9sPLPI2MS3JYEL3pf0J2Kp0lBzoS9Iu0K/FJ7t7lg2wIAlul/qPrPjuPA12Cl+XWL6GKNr78ZxoTJb3+LPY2WmAhfHyZTRs5sIXukZiz84SL5jvlhSN9SeAWHFAJt04cYMGba1gOcb2SZJ/5ANnTiYjzBNlpFt6wnRuQ4LGWO4maOCCg2ss4INy4pBW17+SuDcv7I0D0Vq2HuwemIAG1ItorpLKC4MIVRoVTvzEeb2ydfgYoSs=
