spring:
  application:
    name: okta-springboot-graphql
server:
  port: 9000

okta:  
  oauth2: 
    issuer: ${oktaBaseUrl}/oauth2/default  
    clientId: ${oktaClientId}  
    scopes: 'email profile openid'